import { TailwindIndicator } from "@/components/TailwindIndicator";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SPM 2023",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} min-h-screen scroll-smooth antialiased`}
      >
        <div className="flex flex-col min-h-screen space-y-6">{children}</div>
        <TailwindIndicator />
      </body>
    </html>
  );
}
