name: Run Jest Tests

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main # Replace 'main' with your default branch name

jobs:
  test:
    runs-on: ubuntu-latest

  strategy:
    maxtrix:
      node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js v${{maxtrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{maxtrix.node-version}}

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm run test
